version: "3.9"
services:
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/myapp:cached
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    stdin_open: true
    tty: true
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/myapp:cached
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  # 追加
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - "./data/redis:/data"
volumes:
  node_modules:
  bundle:
